const en_EN = {
  navbar: {
    logo: {
      name: "Socketspace Indonesia",
      img: "ssi-color.png",
    },
    menu: {
      solution: "Solutions",
      product: "Products",
      project: "Projects",
      teams: "Teams",
      contact: "Contact",
    },
  },
  solution: {
    sectionTitle: "Technology Solution for your business",
    solutionContent: [
      {
        id: 1,
        title: "SocketCloud",
        desc: "Find your business to be Reliable and Secure with Cloud Based Architecture for your main server",
        logo: "SocketCloud_Logo.png",
        alt: "SocketCloud - Socketspace Indonesia",
      },
      {
        id: 2,
        title: "DataSpace",
        desc: "Store and access your data for Automation, Scalable, and Secure use to your business operation",
        logo: "DataSpace_Logo.png",
        alt: "DataSpace - Socketspace Indonesia",
      },
      {
        id: 3,
        title: "SocketApp",
        desc: "Develop and deploy your web, mobile, and even your desktop application in an easy way for your business operation",
        logo: "SocketApp_Logo.png",
        alt: "SocketApp - Socketspace Indonesia",
      },
    ],
  },
  product: {
    sectionTitle: "Our Product",
    productContent: [
      {
        id: 1,
        title: "Cloudspace Platform",
        subtitle: "Self-Managed Cloud Powered by Socketspace Indonesia",
        desc: "Cloudspace Platform Description",
        logo: "ssi-color.png",
        alt: "",
        url: "/product",
      },
      {
        id: 2,
        title: "Minera",
        subtitle:
          "Complete ERP System Management on Web Platform for Mining Operation",
        desc: "Minera Description",
        logo: "ssi-color.png",
        alt: "",
        url: "/solution",
      },
      {
        id: 3,
        title: "EMService",
        subtitle:
          "Employement Mangement Service powered by Socketspace Indonesia",
        desc: "EMService Description",
        logo: "ssi-color.png",
        alt: "",
        url: "/",
      },
    ],
    learn: "Learn More",
  },
  project: [],
  teams: {
    sectionTitle: "Our Teams",
    teamsContent: [
      {
        id: 1,
        name: "Muhammad Jihad Abdurrohman",
        position: "Chief of Executive Officer (CEO)",
        img: "teams/jihadabdurrohman.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 2,
        name: "Prasetya Ikra Priyadi",
        position: "Operation Manager",
        img: "teams/prasetyaikrap.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 3,
        name: "Rima Martatia",
        position: "Finance Manager",
        img: "teams/rimamartatia.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 4,
        name: "Rifqi Finaldy",
        position: "Technology and Development Manager",
        img: "teams/rifqifinaldy.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 5,
        name: "Faishal Amrullah",
        position: "Marketing Manager",
        img: "teams/faishalamrullah.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 6,
        name: "Ahmad Ashary Yuwono",
        position: "Project Manager",
        img: "teams/ahmadashary.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 7,
        name: "Muhammad Nizar Marifat",
        position: "Fullstack Developer",
        img: "teams/nizarmarifat.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 8,
        name: "Firdaus Arifin",
        position: "Backend Developer",
        img: "team-img.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
      {
        id: 9,
        name: "Muhammad Rafli",
        position: "Backend Developer",
        img: "team-img.png",
        linkedin: "Linkedin",
        linkedinurl: "/",
        instagram: "@instagram",
        instagramurl: "/",
      },
    ],
  },
  contact: {
    name: "MAIN OPERATIONAL OFFICE",
    address:
      "St. Jatiarum No.27B, Pasirjati, Kec. Cilengkrang, Kabupaten Bandung, Jawa Barat 40616",
    openDays: "Monday - Friday",
    openHours: "09.00 - 17.00 WIB",
    email1: "company@socketspace.com",
    email2: "marketing@socketspace.com",
    socialmedia: [
      {
        id: 1,
        name: "Linkedin",
        desc: "Socketspace Indonesia",
        color: "#0072b1",
        icon: "",
        url: "https://id.linkedin.com/company/socketspace",
      },
      {
        id: 2,
        name: "Instagram",
        desc: "Socketspace Indonesia",
        color: "#bc2a8d",
        icon: "",
        url: "https://www.instagram.com/socketspace/",
      },
      {
        id: 3,
        name: "Youtube",
        color: "#FF0000",
        icon: "",
        desc: "Socketspace Indonesia",
        url: "https://www.youtube.com/channel/UClmxjjhsZqv602T1EhR34GA/featured",
      },
      {
        id: 4,
        name: "Whatsapp",
        desc: "Socketspace Indonesia",
        color: "#25D366",
        icon: "",
        url: "https://api.whatsapp.com/send/?phone=6281220100516&text=Halo+Socketspace",
      },
    ],
  },
};

const id_ID = {
  navbar: {
    logo: {
      name: "Socketspace Indonesia",
      img: "ssi-color.png",
    },
    menu: {
      solution: "Solusi",
      product: "Produk",
      project: "Project",
      teams: "Tim",
      contact: "Kontak",
    },
  },
  solution: {
    sectionTitle: "Solusi Teknologi untuk kebutuhan bisnis anda",
    solutionContent: [
      {
        id: 1,
        title: "SocketCloud",
        desc: "Membangun bisnis yang dapat dihandalkan di era digital dengan mengadopsi Cloud Architecture Technology untuk infrastruktur server anda",
        logo: "SocketCloud_Logo.png",
        alt: "SocketCloud - Socketspace Indonesia",
      },
      {
        id: 2,
        title: "DataSpace",
        desc: "Simpan dan kelola data anda dengan Cepat dan Aman dengan Skalabilitas dan Otomasi yang tinggi bagi opersional bisnis anda",
        logo: "DataSpace_Logo.png",
        alt: "DataSpace - Socketspace Indonesia",
      },
      {
        id: 3,
        title: "SocketApp",
        desc: "Rencanakan, desain, kembangkan, dan luncurkan aplikasi anda pada platform Web, Mobile, maupun Desktop sesuai dengan kebutuhan bisnis anda",
        logo: "SocketApp_Logo.png",
        alt: "SocketApp - Socketspace Indonesia",
      },
    ],
  },
  product: {
    sectionTitle: "Our Product",
    productContent: [
      {
        id: 1,
        title: "Cloudspace Platform",
        subtitle: "Self-Managed Cloud Powered by Socketspace Indonesia",
        desc: "Cloudspace Platform Description",
        logo: "ssi-color.png",
        alt: "",
        url: "/",
      },
      {
        id: 2,
        title: "Minera",
        subtitle:
          "Complete ERP System Management on Web Platform for Mining Operation",
        desc: "Minera Description",
        logo: "ssi-color.png",
        alt: "",
        url: "/",
      },
      {
        id: 3,
        title: "EMService",
        subtitle:
          "Employement Mangement Service powered by Socketspace Indonesia",
        desc: "EMService Description",
        logo: "ssi-color.png",
        alt: "",
        url: "/",
      },
    ],
    learn: "Pelajari",
  },
  project: [],
  teams: {
    sectionTitle: "Tim Kami",
    teamsContent: [
      {
        name: "Muhammad Jihad Abdurrohman",
        position: "Chief of Executive Officer (CEO)",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Prasetya Ikra Priyadi",
        position: "Operation Manager",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Rima Martatia",
        position: "Finance Manager",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Rifqi Finaldy",
        position: "Technology and Development Manager",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Faishal Amrullah",
        position: "Marketing Manager",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Ahmad Ashary Yuwono",
        position: "Project Manager",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Muhammad Nizar Marifat",
        position: "Fullstack Developer",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Firdaus Arifin",
        position: "Backend Developer",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
      {
        name: "Muhammad Rafli",
        position: "Backend Developer",
        img: "",
        linkedin: "",
        linkedinurl: "",
        instagram: "",
        instagramurl: "",
      },
    ],
  },
  contact: {
    name: "",
    address: "",
    email1: "",
    email2: "",
    socialmedia: [
      {
        id: 1,
        name: "Linkedin",
        desc: "Socketspace Indonesia",
        icon: "",
        url: "https://www.linkedin.com/company/socketspace/",
      },
      {
        id: 2,
        name: "Instagram",
        desc: "Socketspace Indonesia",
        icon: "",
        url: "https://www.instagram.com/socketspace/",
      },
      {
        id: 3,
        name: "Youtube",
        icon: "",
        desc: "Socketspace Indonesia",
        url: "https://www.youtube.com/channel/UClmxjjhsZqv602T1EhR34GA/featured",
      },
      {
        id: 4,
        name: "Whatsapp",
        desc: "Socketspace Indonesia",
        icon: "",
        url: "https://api.whatsapp.com/send/?phone=6281220100516&text=Halo+Socketspace",
      },
    ],
  },
};
const content = {
  en_EN: en_EN,
  id_ID: id_ID,
};

const SolutionContent = [
  {
    id: 1,
    title: "SocketCloud",
    desc: "Membangun bisnis yang dapat dihandalkan di era digital dengan mengadopsi Cloud Architecture Technology untuk infrastruktur server anda",
    logo: "SocketCloud_Logo.png",
    alt: "SocketCloud - Socketspace Indonesia",
  },
  {
    id: 2,
    title: "DataSpace",
    desc: "Simpan dan kelola data anda dengan Cepat dan Aman dengan Skalabilitas dan Otomasi yang tinggi bagi opersional bisnis anda",
    logo: "DataSpace_Logo.png",
    alt: "DataSpace - Socketspace Indonesia",
  },
  {
    id: 3,
    title: "SocketApp",
    desc: "Rencanakan, desain, kembangkan, dan luncurkan aplikasi anda pada platform Web, Mobile, maupun Desktop sesuai dengan kebutuhan bisnis anda",
    logo: "SocketApp_Logo.png",
    alt: "SocketApp - Socketspace Indonesia",
  },
];

const ProductContent = [
  {
    id: 1,
    title: "Cloudspace Platform",
    subtitle: "Self-Managed Cloud Powered by Socketspace Indonesia",
    desc: "Cloudspace Platform Description",
    logo: "ssi-color.png",
    alt: "",
  },
  {
    id: 2,
    title: "Minera",
    subtitle:
      "Complete ERP System Management on Web Platform for Mining Operation",
    desc: "Minera Description",
    logo: "ssi-color.png",
    alt: "",
  },
  {
    id: 3,
    title: "EMService",
    subtitle: "Employement Mangement Service powered by Socketspace Indonesia",
    desc: "EMService Description",
    logo: "ssi-color.png",
    alt: "",
  },
];

const ProjectContent = [];
const TeamsContent = [];
//export
export default content;
export { SolutionContent, ProductContent, ProjectContent, TeamsContent };
